### PR TITLE
Rearrange paper as per reviewer comment

### PR DESCRIPTION
**Pull request by gaurav**
One of our reviewers [suggested rearranging the paper a bit](https://github.com/openjournals/joss-reviews/issues/3374#issuecomment-864920022) in their review. This PR is an attempt to do that.

You can see how this [renders on Whedon](https://whedon.theoj.org/preview?id=410abca6fddae409ba5bdc53).

I was hoping to edit the paper only after both reviewer comments were in, but I suppose we might as well start this discussion now.

### CODE REVIEW

**Comment by hlapp** [comment]
I don't think this is a useful rearrangement at all. Sacrificing a summary statement at the beginning, which gives readers the benefit of getting an overview before having to decide to read the full text, for a statement of need at the end, a place where by definition it can't help anyone better understand what was written (and what they needed to read) before, seems misguided.

I'll read through the manuscript one more time, but my hunch is that we may need to push back against the reviewer request. More specifically, if the issue is indeed not about whether a statement of need is present (which is the basic requirement set forth by JOSS) or lacking or insufficient, but primarily about whether a heading "Statement of Need" is present or not, which, in my reading, is not what is strictly required by JOSS, then I would argue we fulfill the requirement, and the additional request is not well justified.

That said, perhaps the fact that there is a statement of need already in the manuscript is not as obvious as it could be, and perhaps some small changes can be made to address that. That's I think the question that need to be evaluated by re-reading with this in mind.

**Comment by gaurav** [comment]
Sounds good! Yes, I thought we might want to push back against the reviewer request, which is why I thought it would be best to do this once both reviews were in and it was time to write a response to the editor. I think the plan you outline sounds great.

**Comment by hlapp** [comment]
OK, how about you return this to draft stage then.

**Comment by gaurav** [comment]
Done!

**Comment by ncellinese** [comment]
Yes, I would wait for both reviews to be in. It would be better to see what he has to say if anything.

Nico

**Comment by gaurav** [comment]
Superceded by PR #96, closing.

**Pull request closed without merging**
