### PR TITLE
Updated Cellinese 2021 citation to "accepted"

### PR DESCRIPTION
**Pull request by gaurav**
This PR updates the citation status of the Cellinese 2021 citation to indicate that it has been accepted to *Philosophy, Theory and Practice in Biology*, and tweaks the BibTeX to fix the capitalization of the paper title as well.

### CODE REVIEW

**Comment by hlapp** [comment]
@gaurav FYI, the link to the generated preview PDF already doesn't work anymore. I think it's best not to post these as they seem to expire very quickly and do not seem to meant for dissemination.

Also, as an aside I assume you're still working on this?

**Comment by gaurav** [comment]
Sorry, got sidetracked by a meeting and then took a while to get back to this. Yes, it's good to go!

**Review by hlapp — CHANGES_REQUESTED** [review]
The way you're changing it you're changing it you're declaring the URL of the PTPBio paper the URL of the preprint. I don't think that's correct. So maybe add the URL to `pages`? Or don't give a URL.

**Comment by gaurav** [comment]
> So maybe add the URL to `pages`? Or don't give a URL.

I can add it to the `pages` field, and it continues to work perfectly as a link, but for some reason it isn't coloured blue like the other hyperlinks. I think that's fine, but I could also just take it out entirely if that would be better.

**Comment by ncellinese** [comment]
We can only cite the preprint URL right now and state it is accepted in PTPB. Just cut and copy as I have it in my website

**Review by hlapp — APPROVED** [review]
I think this works fine.

**Comment by hlapp** [comment]
> Just cut and copy as I have it in my website

@nico this won't work because references have to given in a BibTeX file.

**Comment by ncellinese** [comment]
Sorry, I meant just the content, not the format.

Nico

**Pull request merged**
